import React, { useState } from 'react';
import { ChevronLeft, Clock3, Database, Film, Info, Radio, Search, Server, Settings, Trash2, Check, Download, Upload } from 'lucide-react';
import { LiveFeature } from '../features/live/LiveFeature.jsx';
import { SmartImage, EmptyState } from '../components/StateViews.jsx';

function Main({tab,movies,channels,favorites,history,sources,searches,progress,onTab,onMovie,onLive,onLiveChannel,onSearchHistory,toggleFavorite,onClearData,onClearCache,onSourceEnabled,onRemoveSource}){
 const [favoriteSection,setFavoriteSection]=useState('movies');
 const [confirm,setConfirm]=useState(null);
 if(tab==='live') return <LiveFeature channels={channels} favorites={favorites} onChannel={onLiveChannel} onPlay={onLive} onTab={onTab} toggleFavorite={toggleFavorite}/>;
 if(tab==='favorites'){
  const favMovies=movies.filter(m=>favorites.some(i=>i.targetType==='content'&&i.targetId===m.contentId));
  const favChannels=channels.filter(c=>favorites.some(i=>i.targetType==='channel'&&i.targetId===c.channelId));
  return <Page><Header title="收藏"/><div className="seg"><button className={favoriteSection==='movies'?'active':''} onClick={()=>setFavoriteSection('movies')}>影视</button><button className={favoriteSection==='live'?'active':''} onClick={()=>setFavoriteSection('live')}>Live</button></div>{favoriteSection==='movies'?<><MovieGrid movies={favMovies} onMovie={onMovie}/>{!favMovies.length&&<Empty text="还没有影视收藏"/>}</>:<div className="channel-list">{favChannels.map(c=><button className="menu" key={c.channelId} onClick={()=>onLiveChannel(c)}><Radio size={18}/><span>{c.name}<small>{c.category} · {c.streams.length} 条线路</small></span><ChevronLeft className="flip" size={17}/></button>)}{!favChannels.length&&<Empty text="还没有 Live 收藏"/>}</div>}</Page>;
 }
 if(tab==='history'){
  const historyMovies=history.filter(i=>i.targetType==='content').map(item=>({item,movie:movies.find(m=>m.contentId===item.targetId)})).filter(x=>x.movie);
  const historyChannels=history.filter(i=>i.targetType==='channel').map(i=>channels.find(c=>c.channelId===i.targetId)).filter(Boolean);
  return <Page><Header title="播放历史"/>{historyMovies.length?<div className="movie-grid">{historyMovies.map(({movie,item})=>{const ep=movie.episodes?.find(e=>e.episodeId===item.episodeId);const pct=item.durationSeconds?Math.min(100,Math.round(item.positionSeconds/item.durationSeconds*100)):0;return <article className="movie-card history-card" key={item.historyId} onClick={()=>onMovie(movie)}><SmartImage src={movie.poster} alt={movie.title}/><div><b>{movie.title}</b><span>{ep?.title??'继续观看'} · {pct}%</span><small>最近观看：{new Date(item.lastPlayedAt||Date.now()).toLocaleString()}</small></div></article>})}</div>:<Empty text="还没有播放历史"/>}{historyChannels.length>0&&<><SectionTitle title="Live"/><div className="channel-list">{historyChannels.map(c=><button className="menu" key={c.channelId} onClick={()=>onLiveChannel(c)}><Radio size={18}/><span>{c.name}<small>{c.category}</small></span><ChevronLeft className="flip" size={17}/></button>)}</div></>}</Page>;
 }
 if(tab==='search-history') return <Page><Header title="搜索历史"/><div className="actions"><button className="secondary" disabled={!searches.length} onClick={()=>setConfirm({type:'searches'})}>清空搜索历史</button></div><div className="history-list">{searches.map(i=><div className="menu" key={i.searchId}><Search size={18}/><button className="history-keyword" onClick={()=>onSearchHistory(i.keyword)}>{i.keyword}</button><em>{i.count} 次</em><button className="icon-button" aria-label="删除历史" onClick={()=>setConfirm({type:'search',id:i.searchId})}>×</button></div>)}{!searches.length&&<Empty text="还没有搜索历史"/>}</div>{confirm&&<ConfirmDialog title={confirm.type==='searches'?'清空搜索历史？':'删除这条搜索历史？'} onCancel={()=>setConfirm(null)} onConfirm={()=>{if(confirm.type==='searches')onClearSearches();else onRemoveSearch(confirm.id);setConfirm(null)}}/>}</Page>;
 if(tab==='sources') return <Page><Header title="源管理"/><div className="actions"><button className="secondary"><Upload size={16}/>导入</button><button className="secondary"><Download size={16}/>导出</button></div><SectionTitle title="影视源"/><SourceList sources={sources.filter(s=>s.sourceType==='movie')} onEnabled={onSourceEnabled} onRemove={onRemoveSource}/><SectionTitle title="Live 源"/><SourceList sources={sources.filter(s=>s.sourceType==='live')} onEnabled={onSourceEnabled} onRemove={onRemoveSource}/><InfoCard title="源边界" text="影视源与 Live 源独立管理。当前页面提供启用/停用、删除入口；导入/导出入口保留给源管理协议实现。"/></Page>;
 if(tab==='settings') return <Page><Header title="设置"/><SectionTitle title="播放设置"/><Menu icon={Radio} title="自动继续播放"/><Menu icon={Radio} title="默认播放线路"/><SectionTitle title="外观设置"/><Menu icon={Settings} title="主题"/><Menu icon={Settings} title="字体"/><Menu icon={Settings} title="卡片显示"/><Menu icon={Settings} title="显示密度"/><SectionTitle title="数据设置"/><Menu icon={Trash2} title="清除历史" onClick={()=>setConfirm({type:'history'})}/><Menu icon={Trash2} title="清除搜索记录" onClick={()=>setConfirm({type:'searches'})}/><Menu icon={Database} title="清除缓存" onClick={()=>{onClearCache();}}/>{confirm&&<ConfirmDialog title="确认清理？" onCancel={()=>setConfirm(null)} onConfirm={()=>{onClearData();setConfirm(null)}}/>}</Page>;
 if(tab==='data-management') return <Page><Header title="数据管理"/><Menu icon={Trash2} title="清理用户数据" onClick={()=>setConfirm({type:'all'})}/><Menu icon={Database} title="清理缓存" onClick={onClearCache}/><InfoCard title="不可逆操作" text="用户数据清理会删除收藏、历史、播放进度和搜索历史；源配置不会删除。"/>{confirm&&<ConfirmDialog title="确认清理用户数据？" onCancel={()=>setConfirm(null)} onConfirm={()=>{onClearData();setConfirm(null)}}/>}</Page>;
 if(tab==='about') return <Page><Header title="关于"/><InfoCard title="TVBox React" text="安卓手机竖屏影视与 Live 内容聚合应用。"/><InfoCard title="版本" text="0.3.0 · 产品架构实现版"/><InfoCard title="版权与开源" text="本项目遵循仓库中声明的开源与第三方依赖许可要求。"/><InfoCard title="架构" text="影视、Live、用户数据、源管理与播放内核保持独立边界。"/></Page>;
 return <Page><Header title="我的"/><div className="profile"><div className="avatar">T</div><div><b>TVBox 用户</b><span>本地数据独立存储 · 产品架构版</span></div></div><Menu icon={Clock3} title="播放历史" onClick={()=>onTab('history')} badge={history.length}/><Menu icon={Search} title="搜索历史" onClick={()=>onTab('search-history')} badge={searches.length}/><Menu icon={Server} title="源管理" onClick={()=>onTab('sources')} badge={sources.length}/><Menu icon={Settings} title="设置" onClick={()=>onTab('settings')}/><Menu icon={Database} title="数据管理" onClick={()=>onTab('data-management')}/><Menu icon={Info} title="关于" onClick={()=>onTab('about')}/></Page>;
}
function SourceList({sources,onEnabled,onRemove}){return <div className="source-list">{sources.map(source=><div className="menu source-row" key={source.sourceId}><Server size={19}/><span><b>{source.name}</b><small>{source.sourceType} · {source.status} {source.isActive?'· 当前使用':''}</small></span><button className="secondary" onClick={()=>onEnabled(source.sourceId,!source.enabled)}>{source.enabled?<><Check size={15}/>停用</>:<>启用</>}</button><button className="icon-button" onClick={()=>onRemove(source.sourceId)} aria-label="删除源">×</button></div>)}{!sources.length&&<Empty text="暂无内容源"/>}</div>}
const ConfirmDialog=({title,onCancel,onConfirm})=><div className="modal-backdrop"><div className="modal"><b>{title}</b><div className="actions"><button className="secondary" onClick={onCancel}>取消</button><button className="primary" onClick={onConfirm}>确认</button></div></div></div>;
const Page=({children})=><main className="page">{children}</main>;
const Header=({title})=><header><div><span className="eyebrow">TVBOX REACT</span><h2>{title}</h2></div></header>;
const SectionTitle=({title})=><div className="section-title"><h3>{title}</h3></div>;
const InfoCard=({title,text})=><div className="info-card"><Info size={18}/><div><b>{title}</b><span>{text}</span></div></div>;
const Empty=({text})=><div className="empty"><Film size={22}/><span>{text}</span></div>;
const MovieGrid=React.memo(function MovieGrid({movies,onMovie}){return <div className="movie-grid">{movies.map(movie=><article className="movie-card" key={movie.contentId} onClick={()=>onMovie(movie)}><SmartImage src={movie.poster} alt={movie.title}/><div><b>{movie.title}</b><span>{movie.year} · {movie.category}</span></div></article>)}</div>});
const Menu=({icon:Icon,title,onClick,badge})=><button className="menu" onClick={onClick}><Icon size={19}/><span>{title}</span>{badge>0&&<em>{badge}</em>}<ChevronLeft className="flip" size={17}/></button>;
export {Main as MainPage};
