import React, { useState } from 'react';
import { ChevronLeft, Clock3, Database, Film, Info, Radio, Search, Server, Settings, Trash2, Check, Download, Upload } from 'lucide-react';
import { LiveFeature } from '../features/live/LiveFeature.jsx';
import { SmartImage, EmptyState } from '../components/StateViews.jsx';
import { sourceConfigService } from '../services/sourceConfigService.js';

function Main({tab,movies,channels,favorites,history,sources,searches,progress,onTab,onMovie,onLive,onLiveChannel,onSearchHistory,toggleFavorite,onClearData,onClearHistory,onSaveSources,onClearSearches,onRemoveSearch,onClearCache,onSourceEnabled,onSourceActive,onTestSource,onRemoveSource}){
 const [favoriteSection,setFavoriteSection]=useState('movies');
 const [confirm,setConfirm]=useState(null); const [sourceForm,setSourceForm]=useState(null);
 if(tab==='live') return <LiveFeature channels={channels} favorites={favorites} onChannel={onLiveChannel} onPlay={onLive} onTab={onTab} toggleFavorite={toggleFavorite}/>;
 if(tab==='favorites'){
  const favoriteContentRecords=favorites.filter(i=>i.targetType==='content');
  const favMovies=favoriteContentRecords.map(record=>movies.find(m=>m.contentId===record.targetId)||{contentId:record.targetId,title:'暂时无法找到来源',year:'',category:'',poster:'',unresolved:true});
  const favChannels=channels.filter(c=>favorites.some(i=>i.targetType==='channel'&&i.targetId===c.channelId));
  return <Page><Header title="收藏"/><div className="seg"><button className={favoriteSection==='movies'?'active':''} onClick={()=>setFavoriteSection('movies')}>影视</button><button className={favoriteSection==='live'?'active':''} onClick={()=>setFavoriteSection('live')}>Live</button></div>{favoriteSection==='movies'?<><MovieGrid movies={favMovies.filter(movie=>!movie.unresolved)} onMovie={onMovie}/>{favMovies.filter(movie=>movie.unresolved).map(movie=><div className="info-card" key={movie.contentId}><Database size={18}/><div><b>暂时无法找到来源</b><span>收藏仍已保留：{movie.contentId}</span></div></div>)}{!favMovies.length&&<Empty text="还没有影视收藏"/>}</>:<div className="channel-list">{favChannels.map(c=><button className="menu" key={c.channelId} onClick={()=>onLiveChannel(c)}><Radio size={18}/><span>{c.name}<small>{c.category} · {c.streams.length} 条线路</small></span><ChevronLeft className="flip" size={17}/></button>)}{!favChannels.length&&<Empty text="还没有 Live 收藏"/>}</div>}</Page>;
 }
 if(tab==='history'){
  const historyMovies=history.filter(i=>i.targetType==='content').map(item=>({item,movie:movies.find(m=>m.contentId===item.targetId)||null}));
  const historyChannels=history.filter(i=>i.targetType==='channel').map(i=>channels.find(c=>c.channelId===i.targetId)).filter(Boolean);
  return <Page><Header title="播放历史"/>{historyMovies.length?<div className="movie-grid">{historyMovies.filter(({movie})=>movie).map(({movie,item})=>{const ep=movie.episodes?.find(e=>e.episodeId===item.episodeId);const pct=item.durationSeconds?Math.min(100,Math.round(item.positionSeconds/item.durationSeconds*100)):0;return <article className="movie-card history-card" key={item.historyId} onClick={()=>onMovie(movie)}><SmartImage src={movie.poster} alt={movie.title}/><div><b>{movie.title}</b><span>{ep?.title??'继续观看'} · {pct}%</span><small>最近观看：{new Date(item.lastPlayedAt||Date.now()).toLocaleString()}</small></div></article>})}</div>:<Empty text="还没有播放历史"/>}{historyMovies.filter(({movie})=>!movie).map(({item})=><div className="info-card" key={item.historyId}><Database size={18}/><div><b>暂时无法找到来源</b><span>播放历史已保留：{item.targetId}</span></div></div>)}{historyChannels.length>0&&<><SectionTitle title="Live"/><div className="channel-list">{historyChannels.map(c=><button className="menu" key={c.channelId} onClick={()=>onLiveChannel(c)}><Radio size={18}/><span>{c.name}<small>{c.category}</small></span><ChevronLeft className="flip" size={17}/></button>)}</div></>}</Page>;
 }
 if(tab==='search-history') return <Page><Header title="搜索历史"/><div className="actions"><button className="secondary" disabled={!searches.length} onClick={()=>setConfirm({type:'searches'})}>清空搜索历史</button></div><div className="history-list">{searches.map(i=><div className="menu" key={i.searchId}><Search size={18}/><button className="history-keyword" onClick={()=>onSearchHistory(i.keyword)}>{i.keyword}</button><em>{i.count} 次</em><button className="icon-button" aria-label="删除历史" onClick={()=>setConfirm({type:'search',id:i.searchId})}>×</button></div>)}{!searches.length&&<Empty text="还没有搜索历史"/>}</div>{confirm&&<ConfirmDialog title={confirm.type==='searches'?'清空搜索历史？':'删除这条搜索历史？'} onCancel={()=>setConfirm(null)} onConfirm={()=>{if(confirm.type==='searches')onClearSearches();else onRemoveSearch(confirm.id);setConfirm(null)}}/>}</Page>;
 if(tab==='sources') return <Page><Header title="源管理"/><div className="actions"><button className="secondary" onClick={()=>setSourceForm({sourceType:'movie',name:''})}>添加源</button><button className="secondary" onClick={()=>sourceConfigService.download(sources)}><Download size={16}/>导出</button><label className="secondary file-button"><Upload size={16}/>导入<input type="file" accept="application/json" hidden onChange={async e=>{const file=e.target.files?.[0];if(!file)return;try{const parsed=await sourceConfigService.importFile(file);await onSaveSources(parsed)}catch(error){console.error(error)}finally{e.target.value=''}}}/></label></div><SectionTitle title="影视源"/><SourceList sources={sources.filter(s=>s.sourceType==='movie')} onEnabled={onSourceEnabled} onActive={onSourceActive} onTest={onTestSource} onRemove={onRemoveSource}/><SectionTitle title="Live 源"/><SourceList sources={sources.filter(s=>s.sourceType==='live')} onEnabled={onSourceEnabled} onActive={onSourceActive} onTest={onTestSource} onRemove={onRemoveSource}/><InfoCard title="源边界" text="影视源与 Live 源独立管理。添加、启用/停用、删除、导入与导出均只操作本地源配置。"/>{sourceForm&&<SourceForm value={sourceForm} onCancel={()=>setSourceForm(null)} onSave={source=>{onSaveSources([...sources,{...source,enabled:true,status:'未测试'}]);setSourceForm(null)}}/>}</Page>;
 if(tab==='settings') return <Page><Header title="设置"/><SectionTitle title="播放设置"/><Menu icon={Radio} title="自动继续播放"/><Menu icon={Radio} title="默认播放线路"/><SectionTitle title="外观设置"/><Menu icon={Settings} title="主题"/><Menu icon={Settings} title="字体"/><Menu icon={Settings} title="卡片显示"/><Menu icon={Settings} title="显示密度"/><SectionTitle title="数据设置"/><Menu icon={Trash2} title="清除历史" onClick={()=>setConfirm({type:'history'})}/><Menu icon={Trash2} title="清除搜索记录" onClick={()=>setConfirm({type:'searches'})}/><Menu icon={Database} title="清除缓存" onClick={()=>{onClearCache();}}/>{confirm&&<ConfirmDialog title="确认清理？" onCancel={()=>setConfirm(null)} onConfirm={()=>{if(confirm.type==='history')onClearHistory();else onClearSearches();setConfirm(null)}}/>}</Page>;
 if(tab==='data-management') return <Page><Header title="数据管理"/><Menu icon={Trash2} title="清理用户数据" onClick={()=>setConfirm({type:'all'})}/><Menu icon={Database} title="清理缓存" onClick={onClearCache}/><InfoCard title="不可逆操作" text="用户数据清理会删除收藏、历史、播放进度和搜索历史；源配置不会删除。"/>{confirm&&<ConfirmDialog title="确认清理用户数据？" onCancel={()=>setConfirm(null)} onConfirm={()=>{onClearData();setConfirm(null)}}/>}</Page>;
 if(tab==='about') return <Page><Header title="关于"/><InfoCard title="TVBox React" text="安卓手机竖屏影视与 Live 内容聚合应用。"/><InfoCard title="版本" text="0.3.0 · 产品架构实现版"/><InfoCard title="版权与开源" text="本项目遵循仓库中声明的开源与第三方依赖许可要求。"/><InfoCard title="架构" text="影视、Live、用户数据、源管理与播放内核保持独立边界。"/></Page>;
 return <Page><Header title="我的"/><div className="profile"><div className="avatar">T</div><div><b>TVBox 用户</b><span>本地数据独立存储 · 产品架构版</span></div></div><Menu icon={Clock3} title="播放历史" onClick={()=>onTab('history')} badge={history.length}/><Menu icon={Search} title="搜索历史" onClick={()=>onTab('search-history')} badge={searches.length}/><Menu icon={Server} title="源管理" onClick={()=>onTab('sources')} badge={sources.length}/><Menu icon={Settings} title="设置" onClick={()=>onTab('settings')}/><Menu icon={Database} title="数据管理" onClick={()=>onTab('data-management')}/><Menu icon={Info} title="关于" onClick={()=>onTab('about')}/></Page>;
}
function SourceList({sources,onEnabled,onActive,onTest,onRemove}){return <div className="source-list">{sources.map(source=><div className="menu source-row" key={source.sourceId}><Server size={19}/><span><b>{source.name}</b><small>{source.sourceType} · {source.status} {source.isActive?'· 当前使用':''}</small></span><button className={source.isActive?'primary':'secondary'} onClick={()=>onActive?.(source.sourceId)}>{source.isActive?'当前使用':'设为当前'}</button><button className="secondary" onClick={()=>onTest(source)}>测试</button><button className="secondary" onClick={()=>onEnabled(source.sourceId,!source.enabled)}>{source.enabled?<><Check size={15}/>停用</>:<>启用</>}</button><button className="icon-button" onClick={()=>onRemove(source.sourceId)} aria-label="删除源">×</button></div>)}{!sources.length&&<Empty text="暂无内容源"/>}</div>}
const SourceForm=({value,onCancel,onSave})=>{const [name,setName]=useState(value.name);const [url,setUrl]=useState(value.url||'');const [sourceType,setSourceType]=useState(value.sourceType);return <div className="modal-backdrop"><div className="modal"><b>添加内容源</b><input value={name} onChange={e=>setName(e.target.value)} placeholder="源名称"/><input value={url} onChange={e=>setUrl(e.target.value)} placeholder="源地址 URL"/><select value={sourceType} onChange={e=>setSourceType(e.target.value)}><option value="movie">影视源</option><option value="live">Live 源</option></select><div className="actions"><button className="secondary" onClick={onCancel}>取消</button><button className="primary" disabled={!name.trim()} onClick={()=>onSave({name:name.trim(),url:url.trim(),sourceType})}>保存</button></div></div></div>};
const ConfirmDialog=({title,onCancel,onConfirm})=><div className="modal-backdrop"><div className="modal"><b>{title}</b><div className="actions"><button className="secondary" onClick={onCancel}>取消</button><button className="primary" onClick={onConfirm}>确认</button></div></div></div>;
const Page=({children})=><main className="page">{children}</main>;
const Header=({title})=><header><div><span className="eyebrow">TVBOX REACT</span><h2>{title}</h2></div></header>;
const SectionTitle=({title})=><div className="section-title"><h3>{title}</h3></div>;
const InfoCard=({title,text})=><div className="info-card"><Info size={18}/><div><b>{title}</b><span>{text}</span></div></div>;
const Empty=({text})=><div className="empty"><Film size={22}/><span>{text}</span></div>;
const MovieGrid=React.memo(function MovieGrid({movies,onMovie}){return <div className="movie-grid">{movies.map(movie=><article className="movie-card" key={movie.contentId} onClick={()=>onMovie(movie)}><SmartImage src={movie.poster} alt={movie.title}/><div><b>{movie.title}</b><span>{movie.year} · {movie.category}</span></div></article>)}</div>});
const Menu=({icon:Icon,title,onClick,badge})=><button className="menu" onClick={onClick}><Icon size={19}/><span>{title}</span>{badge>0&&<em>{badge}</em>}<ChevronLeft className="flip" size={17}/></button>;
export {Main as MainPage};
