import React,{useEffect,useMemo,useState} from 'react';
import {ChevronLeft,Heart,Radio} from 'lucide-react';
import {playbackService} from '../services/playbackService';
import {SmartImage} from '../components/StateViews.jsx';

function PlaybackView({request,kind,onBack,channels=[],favorites=[],onChannel,onPlay,toggleFavorite}){
 const [status,setStatus]=useState('idle'); const [candidate,setCandidate]=useState(request?.candidates?.[0]??null); const [resolvedInput,setResolvedInput]=useState(null); const [error,setError]=useState(''); const videoRef=React.useRef(null);

 const controller=useMemo(()=>playbackService.createController(request,{onEvent:e=>{if(e.event==='error')setError(e.error||'播放候选失败');if(e.event==='released')setStatus('released');if(e.event==='stopped')setStatus('stopped')},onStateChange:setStatus,onCandidateChange:next=>{setCandidate(next);setResolvedInput(null);if(next)setError('')},onResolvedInput:setResolvedInput,onParserError:({code})=>setError('解析失败：'+code),onPlayerError:({error:e})=>setError(e?.message||'播放器加载失败'),onExhausted:()=>setStatus('error')}),[request]);
 useEffect(()=>{const onVisibility=()=>void controller.handleAppState(document.visibilityState==='hidden'?'background':'foreground'); document.addEventListener('visibilitychange',onVisibility); const player=controller.attachPlayer(videoRef.current);const initial=controller.start();setCandidate(initial);if(!initial){setStatus('error');setError('没有可用的播放候选')}else controller.resolveAndLoad(initial).catch(e=>setError(e?.message||'播放初始化失败'));return()=>{document.removeEventListener('visibilitychange',onVisibility);controller.leave();void player}},[controller]);
 const channel=channels.find(c=>c.channelId===request?.channelId); const now=Date.now(); const currentProgram=channel?.epg?.find(program=>program.status==='live' || (Date.parse(program.startAt)<=now && now<Date.parse(program.endAt))); const nextProgram=channel?.epg?.find(program=>program.status==='upcoming' || Date.parse(program.startAt)>now); const favorite=favorites.some(i=>i.targetType==='channel'&&i.targetId===channel?.channelId);
 const switchCandidate=id=>{const next=controller.switchCandidate(id);if(next){setCandidate(next);setResolvedInput(null)}};
 const switchChannel=next=>{if(next)onPlay?.(next)};
 const index=channel?channels.findIndex(c=>c.channelId===channel.channelId):-1; const prev=index>0?channels[index-1]:null; const next=index>=0&&index<channels.length-1?channels[index+1]:null;
 return <div className="player-page"><button className="back player-back" onClick={onBack}><ChevronLeft/>退出直播</button><div className="video-wrap"><video ref={videoRef} controls playsInline/>{!resolvedInput&&candidate&&status!=='error'&&<div className="video-overlay">正在解析播放地址…</div>}{status==='error'&&<div className="video-error"><b>播放失败</b><span>{error||'当前播放链路没有可用候选。'}</span><button className="secondary" onClick={()=>{setError('');const retry=controller.start();if(retry)controller.resolveAndLoad(retry).catch(e=>setError(e?.message||'重新加载失败'));}}>重新播放</button><button className="secondary" onClick={()=>{const next=request?.candidates?.find(item=>item.candidateId!==candidate?.candidateId&&!controller.failedCandidateIds?.includes(item.candidateId));if(next)switchCandidate(next.candidateId);}}>切换线路</button></div>}</div><div className="player-info"><span className="eyebrow">LIVE · Playback Core</span><h2>{request?.metadata?.title??'直播'}</h2><p>● 正在直播 · {request?.metadata?.category??''} · {request?.candidates?.length??0} 条候选 · 状态：{status==='idle'||status==='loading'?'连接中':status==='error'?'播放失败':'直播中'}</p>{currentProgram&&<p>当前节目：{currentProgram.title||'未命名节目'} · {currentProgram.startAt||'—'}–{currentProgram.endAt||'—'}</p>}{nextProgram&&<p>下一节目：{nextProgram.title||'未命名节目'} · {nextProgram.startAt||'—'}–{nextProgram.endAt||'—'}</p>}{channel&&<div className="player-channel-switch"><button className="secondary" disabled={!prev} onClick={()=>switchChannel(prev)}>上一频道</button><button className="secondary" disabled={!next} onClick={()=>switchChannel(next)}>下一频道</button><button className={favorite?'secondary active-fav':'secondary'} onClick={()=>toggleFavorite?.('channel',channel.channelId)}><Heart size={16} fill={favorite?'currentColor':'none'}/>{favorite?'已收藏':'收藏'}</button></div>}<div className="chips">{request?.candidates?.map(item=><button key={item.candidateId} className={candidate?.candidateId===item.candidateId?'active':''} onClick={()=>switchCandidate(item.candidateId)}>{item.metadata?.label??item.label??item.protocol}</button>)}</div><SectionTitle title="频道列表"/><div className="channel-list">{channels.map(item=><button className="menu" key={item.channelId} onClick={()=>switchChannel(item)}><Radio size={18}/><span>{item.name}<small>{item.category}</small></span><ChevronLeft className="flip" size={17}/></button>)}</div><small>频道：{channel?.name??'—'} · 候选：{candidate?.candidateId??'—'} · 来源：{candidate?.sourceId??'—'} · 解析：{resolvedInput?.protocol??'等待'}</small></div></div>;
}
const SectionTitle=({title})=><div className="section-title"><h3>{title}</h3></div>;
export function PlaybackPage(props){return <PlaybackView {...props}/>;}
